name: Add assets to release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  add-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: DGsUtilityAgency-*
          merge-multiple: true
          path: artifacts

      - name: Debug
        run: |
          ls
          cd artifacts
          ls

      - name: Add assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          gh release upload "${TAG_NAME}" artifacts/DGsUtilityAgency-Windows
          gh release upload "${TAG_NAME}" artifacts/DGsUtilityAgency-Linux
          gh release upload "${TAG_NAME}" artifacts/DGsUtilityAgency-macOS
